{
 "title": "GMT Gateways & Snooper (PRO)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "gw", "query": "gw.*.scu*" },
   { "name": "tr", "query": "tr.ZT00ZM*" },
   { "name": "cm", "query": "nw.*" },
   { "name": "cm_dl", "label": "cm_downlink", "query": "nw.*.*" },
   { "name": "cm_dl_port", "label": "cm_downlink", "query": "nw.*.*.*" }
  ]
 },
 "panels": [
  { "title": "GMT Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gateway operation rates - $gw",
   "type": "graph",
   "description": "Operation rate",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "hertz",
     "label": "MIL events (SIS, ESR); injections (SIS18)"
    }
   ],
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.rate10s, 1)"
    }
   ]
  },
  {
   "title": "system time offset",
   "type": "graph",
   "description": "Offset between TAI and UTC",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "TAI - system time" }
   ],
   "targets": [
    { "target": "aliasByNode(gw.*.*.offset, 1)" }
   ]
  },
  {
   "title": "WR sync status",
   "type": "graph",
   "description": "WR sync status (100=Tracking, 20=No sync, 0=others)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "aliasByNode(gw.*.*.status, 1)" }
   ]
  },
  {
   "title": "gateway eCPU stalls  - $gw",
   "type": "graph",
   "description": "Stall",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "actual stall" }
   ],
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.stallact, 1)"
    }
   ]
  },
  {
   "title": "gateway eCPU stalls - $gw",
   "type": "graph",
   "description": "Stall",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "max stall (streak)" }
   ],
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.stallmax, 1)"
    }
   ]
  },
  { "title": "GMT Snooper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "total messages - $tr",
   "type": "graph",
   "description": "Action counts",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA output" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tr.$tr.action, 1, 0)"
    }
   ]
  },
  {
   "title": "late messages - $tr",
   "type": "graph",
   "description": "Late counts (ZT00ZM1, ZT00ZM2)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA output" }
   ],
   "targets": [
    { "target": "aliasByNode(tr.*.late, 1)" }
   ]
  },
  {
   "title": "early messages - $tr",
   "type": "graph",
   "description": "Early counts (ZT00ZM1, ZT00ZM2)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA output" }
   ],
   "targets": [
    { "target": "aliasByNode(tr.*.early, 1)" }
   ]
  },
  {
   "title": "overflow messages - $tr",
   "type": "graph",
   "description": "Overflow counts (ZT00ZM1, ZT00ZM2)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "# of lost messages @ ECA Q" }
   ],
   "targets": [
    { "target": "aliasByNode(tr.*.overflow, 1)" }
   ]
  }
 ]
}