{
 "title": "GMT Gateways & Snooper (PRO)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gw", "query": "gw.*.scu*" },
   { "name": "tr", "query": "tr.ZT00ZM*" }
  ]
 },
 "panels": [
  {
   "title": "GMT Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway operation rates - $gw",
   "type": "timeseries",
   "description": "Operation rates for WR MIL Gateways",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.rate10s, 1)"
    }
   ]
  },
  {
   "title": "Gateway number of sent MIL messages - All",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(gw.*.$gw.milnum, 1)"
    }
   ]
  },
  {
   "title": "Gateway - message delivery time from ECA deadline to lm32 (max)",
   "type": "timeseries",
   "description": "delivery time = getSysTime() - deadline;",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "target": "aliasByNode(gw.*.*.tcom, 1)" }
   ]
  },
  {
   "title": "Gateway - remaining time budget (min)",
   "type": "timeseries",
   "description": "deadline TM - getSysTime() when lm32 finishes action handling; negative value means 'late'; calculation: 500us - delivery time - processing time - 20us",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expression": "480.0 - $A", "type": "math" }
   ]
  },
  {
   "title": "Gateway - lm32 message processing time (max)",
   "type": "timeseries",
   "description": "time spent when handling the timing message after reception; please ignore the 'helper' data marked by 'B', 'C' and 'D'",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expression": "-10000 + $A", "type": "math" },
    { "expression": "-10000 + $C", "type": "math" }
   ]
  },
  {
   "title": "Gateway number of bursts and late delivery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.millate, 1,3)"
    },
    {
     "target": "aliasByNode(gw.*.$gw.nburst, 1,3)"
    }
   ]
  },
  {
   "title": "Gateway WR offset (includes latency)",
   "type": "timeseries",
   "description": "Offset between TAI (WR) and UTC",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "target": "aliasByNode(gw.*.*.offset, 1)" }
   ]
  },
  {
   "title": "Gateway WR sync",
   "type": "timeseries",
   "description": "WR sync status (100=Tracking, 20=No sync, 0=others)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.*.status, 1, 2)"
    }
   ]
  },
  {
   "title": "Total messages - $tr",
   "type": "timeseries",
   "description": "Total messages received by the snooper nodes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(tr.$tr.action, 1, 0)"
    }
   ]
  },
  {
   "title": "Late messages - $tr",
   "type": "timeseries",
   "description": "Late messages recieved by the snooper nodes",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "aliasByNode(tr.*.late, 1)" }
   ]
  },
  {
   "title": "Early messages - $tr",
   "type": "timeseries",
   "description": "Early messages received by the snooper nodes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "aliasByNode(tr.*.early, 1)" }
   ]
  },
  {
   "title": "Overflow messages - $tr",
   "type": "timeseries",
   "description": "Overflow messages detected by the snooper nodes",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "aliasByNode(tr.*.overflow, 1)" }
   ]
  },
  {
   "title": "Gateway eCPU stalls  - $gw",
   "type": "timeseries",
   "description": "Stall, observation interval = 50000",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/500", "type": "math" }
   ]
  },
  {
   "title": "Gateway eCPU stalls - $gw",
   "type": "timeseries",
   "description": "Stall, observation interval = 50000",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/500", "type": "math" }
   ]
  },
  {
   "title": "GMT Snooper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  }
 ]
}