{
 "title": "GMT Data Master & Network (PRO)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cm", "query": "nw.*" },
   { "name": "cm_dl", "query": "nw.*.*" },
   { "name": "cm_dl_port", "query": "nw.*.*.*" },
   { "name": "dm", "query": "dm.ZT*" }
  ]
 },
 "panels": [
  { "title": "Data Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TX messages - $dm",
   "type": "graph",
   "description": "Message rate of data master\n(cpu0=SIS+HEST, cpu1=CRYRING, cpu2=ESR)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "hertz", "label": "message rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(dm.$dm.cpu*.rate10s), 1, 2)"
    },
    {
     "target": "aliasByNode(dm.$dm.total.rate10s, 1, 2)"
    }
   ]
  },
  {
   "title": "WR sync status",
   "type": "graph",
   "description": "WR sync status\n(100=Tracking, 20=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dm.ZT00ZZ1.wr.status, 1)"
    }
   ]
  },
  { "title": "Network Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TX packets @ layer 1 switch - $cm",
   "type": "graph",
   "description": "TX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nw.$cm.$cm_dl.$cm_dl_port.tx.rate10s, 1, 2, 3)"
    }
   ]
  },
  {
   "title": "RX packets @ layer 1 switch- $cm",
   "type": "graph",
   "description": "RX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nw.$cm.$cm_dl.$cm_dl_port.rx.rate10s, 1, 2, 3)"
    }
   ]
  },
  { "title": "Network Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "late messages at switch layer 1-3",
   "type": "graph",
   "description": "Number of the late actions in the PRO timing network",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.nlate, 2, 3)"
    }
   ]
  },
  {
   "title": "total messages at switch layer 1-3",
   "type": "graph",
   "description": "Number of messages in the PRO timing network",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.nmess, 2, 3)"
    }
   ]
  },
  {
   "title": "minimum time budget at switch layer 1-3 (value > 600us: ok; in case of  a late message, the value is re-initialized)",
   "type": "graph",
   "description": "Maximum difference between deadline and actual time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "µs", "label": "time til deadline @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.dtmin, 2, 3)"
    }
   ]
  },
  {
   "title": "average time budget at switch layer 1-3",
   "type": "graph",
   "description": "Average difference between deadline and actual time",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "µs", "label": "time til deadline @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.dtave, 2, 3)"
    }
   ]
  }
 ]
}