{
 "title": "GMT UNILAC",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "lm", "label": "localmaster", "query": "uni.nw.*" },
   { "name": "lm_dl", "label": "localmaster downlink", "query": "uni.nw.*.*" },
   { "name": "lm_dl_port", "label": "localmaster downlik ports", "query": "uni.nw.*.*.*" },
   { "name": "pz", "query": "uni.pz.*" }
  ]
 },
 "panels": [
  {
   "title": "Pulsezentrale",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX message rate - $pz",
   "type": "timeseries",
   "description": "TX message rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.messrate, 2)"
    }
   ]
  },
  {
   "title": "PZ WR sync - $pz",
   "type": "timeseries",
   "description": "WR sync status\n(100%=Tracking, 20%=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(uni.pz.*.wrsync, 2)"
    }
   ]
  },
  {
   "title": "Cycles (2us diff in cycle length = 5mHz diff in cycle rate) - $pz",
   "type": "timeseries",
   "description": "Cycle rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.mainsf, 2)"
    }
   ]
  },
  {
   "title": "PZ Warnings - $pz",
   "type": "timeseries",
   "description": "Warnings count of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.warncnt, 2)"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "TX packet rate of the localmaster WRS:\nUNIPZ or DM @wri15, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.2.value), 'wri2 (distr. WRS)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.15.value), 'wri15 (UNIPZ or DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.17.value), 'wri17 (service WRS)', false)"
    }
   ]
  },
  {
   "title": "RX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "RX packet rate of the localmaster WRS:\nUNIPZ or DM @wri15, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.2.value), 'wri2 (distr. WRS)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.15.value), 'wri15 (UNIPZ or DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.17.value), 'wri17 (service WRS)', false)"
    }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Late messages (switch layers 2-3)",
   "type": "timeseries",
   "description": "Number of the late messages in the UNILAC network",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nlate, 2, 3)"
    }
   ]
  },
  {
   "title": "Total messages @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "Total number of messages in the UNILAC network",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nmess, 2, 3)"
    }
   ]
  },
  {
   "title": "Minimum time budget (switch layers 2-3, value > 600us: ok; in case of  a late message, the value is re-initialized)",
   "type": "timeseries",
   "description": "Maximum difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtmin, 2, 3)"
    }
   ]
  },
  {
   "title": "Average time budget @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "Average difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtave, 2, 3)"
    }
   ]
  }
 ]
}