{
 "title": "GMT Data Master & Network (PRO)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "lm", "label": "localmaster", "query": "nw.*" },
   { "name": "lm_dl", "label": "localmaster down-link", "query": "nw.*.*" },
   { "name": "lm_dl_port", "label": "localmaster down-link ports", "query": "nw.*.*.*" },
   { "name": "dm", "query": "dm.ZT*" }
  ]
 },
 "panels": [
  {
   "title": "Data Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX message rates - $dm",
   "type": "timeseries",
   "description": "Message rate of data master\n(cpu0=SIS+HEST, cpu1=CRYRING, cpu2=ESR)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(dm.$dm.cpu0.rate10s, 'SIS18', false)"
    },
    {
     "target": "alias(dm.$dm.cpu1.rate10s, 'Cryring', false)"
    },
    {
     "target": "alias(dm.$dm.cpu2.rate10s, 'ESR', false)"
    }
   ]
  },
  {
   "title": "WR sync status",
   "type": "graph",
   "description": "WR sync status\n(100=Tracking, 20=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dm.ZT00ZZ1.wr.status, 1)"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "TX packet rate of the localmaster WRS:\nprimary DM @wri15, backup DM @wri16, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.2.value), 'wri2 (distr)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.3.value), 'wri3 (distr)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.15.value), 'wri15 (primary DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.16.value), 'wri16 (backup DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.17.value), 'wri17 (service)', false)"
    }
   ]
  },
  {
   "title": "RX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "RX packet rate of the localmaster WRS:\nprimary DM @wri15, backup DM @wri16, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.2.value), 'wri2 (distr.)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.3.value), 'wri3 (distr.)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.15.value), 'wri15 (primary DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.16.value), 'wri16 (backup DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.17.value), 'wri17 (service)', false)"
    }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Late messages (switch layers 1-3)",
   "type": "timeseries",
   "description": "Number of the late messages in the Production network",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.nlate, 2, 3)"
    }
   ]
  },
  {
   "title": "Total messages (switch layers 1-3)",
   "type": "timeseries",
   "description": "Number of TX messages in the Production network",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.nmess, 2, 3)"
    }
   ]
  },
  {
   "title": "Minimum time budget (switch layers 1-3, value > 600us: ok; in case of  a late message, the value is re-initialized)",
   "type": "timeseries",
   "description": "Maximum difference between deadline and actual time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.dtmin, 2, 3)"
    }
   ]
  },
  {
   "title": "Average time budget (switch layers 1-3)",
   "type": "timeseries",
   "description": "Average difference between deadline and actual time",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.PRO.*.*.dtave, 2, 3)"
    }
   ]
  },
  {
   "title": "TX packet rate, Service WRS (nwt0318m66)",
   "type": "timeseries",
   "description": "wri15/16: access (BOOTP), wri13: trunk (tsl101), wri17: access (tsl101, eb-reset)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.txf.13.value), 'wri13 - trunk (tsl101)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.txf.15.value), 'wri15 - access (BOOTP)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.txf.16.value), 'wri16 - access (BOOTP)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.txf.17.value), 'wri17 - access (tsl101)', false)"
    }
   ]
  },
  {
   "title": "RX packet rate, Service WRS (nwt0318m66)",
   "type": "timeseries",
   "description": "wri15/16: access (BOOTP), wri13: trunk (tsl101), wri17: access (tsl101, eb-reset)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 39 },
   "targets": [
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.rxf.13.value), 'wri13 - trunk (tsl101)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.rxf.15.value), 'wri15 - access (BOOTP)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.rxf.16.value), 'wri16 - access (BOOTP)', false)"
    },
    {
     "target": "alias(perSecond(icinga.nwt0318m66.Interfaces.perfdata.rxf.17.value), 'wri17 - access (tsl101)', false)"
    }
   ]
  }
 ]
}