{
 "title": "GMT WRS Temp by Network",
 "description": "WRS status monitored by Icinga",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "wrs", "query": "icinga.nwt*" },
   {
    "name": "prod_wrs",
    "query": "nwt0013m66, nwt0014m66, nwt0021m66, nwt0022m66, nwt0024m66, nwt0026m66, nwt0028m66, nwt0032m66, nwt0038m66, nwt0039m66, nwt0041m66, nwt0047m66, nwt0048m66, nwt0076m66, nwt0077m66, nwt0078m66, nwt0079m66, nwt0082m66, nwt0084m66, nwt0085m66, nwt0086m66, nwt0087m66, nwt0088m66, nwt0089m66, nwt0090m66, nwt0091m66, nwt0092m66, nwt0093m66, nwt0094m66, nwt0095m66, nwt0096m66, nwt0097m66, nwt0098m66, nwt0099m66, nwt0110m66, nwt0113m66, nwt0117m66, nwt0122m66, nwt0179m66, nwt0180m66, nwt0181m66, nwt0182m66, nwt0184m66, nwt0186m66, nwt0226m66, nwt0272m66, nwt0273m66, nwt0275m66, nwt0277m66, nwt0284m66, nwt0287m66, nwt0300m66, nwt0309m66, nwt0310m66, nwt0311m66, nwt0312m66, nwt0313m66, nwt0314m66, nwt0315m66, nwt0316m66, nwt0318m66, nwt0323m66, nwt0324m66, nwt0081m66, nwt0474m66, nwt0475m66, nwt0477m66, nwt0479m66, nwt0482m66, nwt0485m66, nwt0489m66"
   },
   {
    "name": "unilac_wrs",
    "query": "nwt0083m66, nwt0100m66, nwt0478m66, nwt0285m66, nwt0291m66, nwt0292m66, nwt0293m66, nwt0294m66, nwt0303m66, nwt0317m66, nwt0466m66, nwt0480m66, nwt0481m66, nwt0483m66, nwt0484m66, nwt0488m66"
   },
   {
    "name": "int_wrs",
    "query": "nwt0073m66, nwt0103m66, nwt0104m66, nwt0105m66, nwt0106m66, nwt0107m66, nwt0108m66, nwt0111m66, nwt0116m66, nwt0187m66, nwt0283m66, nwt0036m66, nwt0302m66, nwt0486m66, nwt0487m66"
   },
   {
    "name": "ttf_wrs",
    "query": "nwt0009m66, nwt0010m66, nwt0016m66, nwt0018m66, nwt0025m66, nwt0049m66, nwt0050m66, nwt0296m66, nwt0297m66, nwt0469m66"
   }
  ]
 },
 "panels": [
  {
   "title": "WRS FPGA temperature (Production)",
   "type": "timeseries",
   "description": "Top 10 WRSs that have the highest FPGA temperature value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "highestMax(aliasByNode(icinga.$prod_wrs.Temperature.perfdata.sensor.fpga.value, 1), 10)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (Unilac)",
   "type": "timeseries",
   "description": "Top 10 WRSs that have the highest FPGA temperature value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "highestMax(aliasByNode(icinga.$unilac_wrs.Temperature.perfdata.sensor.fpga.value, 1), 10)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (Integration, Uni-Int)",
   "type": "timeseries",
   "description": "Top 10 WRSs that have the highest FPGA temperature value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "highestMax(aliasByNode(icinga.$int_wrs.Temperature.perfdata.sensor.fpga.value, 1), 10)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (TTF)",
   "type": "timeseries",
   "description": "Top 10 WRSs that have the highest FPGA temperature value",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "highestMax(aliasByNode(icinga.$ttf_wrs.Temperature.perfdata.sensor.fpga.value, 1), 10)"
    }
   ]
  }
 ]
}