{
 "title": "GMT Data + Local Master, UNILAC,  PRO",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "lm", "label": "localmaster", "query": "uni.nw.*" },
   { "name": "lm_dl", "label": "localmaster downlink", "query": "uni.nw.*.*" },
   { "name": "lm_dl_port", "label": "localmaster downlik ports", "query": "uni.nw.*.*.*" },
   {
    "name": "dm",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Data Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TX message rate - $dm",
   "type": "timeseries",
   "description": "Data master TX message rate\n(cpu0=UNILAC, period=10s)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(dm.$dm.cpu0.rate10s, 'UNILAC', false)"
    }
   ]
  },
  {
   "title": "WR sync status - $dm",
   "type": "timeseries",
   "description": "WR sync status\n(100=Tracking, 20=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(dm.$dm.wr.status, 'wrsync', false)"
    }
   ]
  },
  {
   "title": "warning rate - $dm",
   "type": "timeseries",
   "description": "Data master warning rate\n(cpu0=UNILAC, period=10s)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(dm.$dm.cpu0.wrate10s, 'UNILAC', false)"
    }
   ]
  },
  {
   "title": "50 Hz Info (mode, lock state, lock rate)",
   "type": "timeseries",
   "description": "Expected values: mode = 4, lock state = 3",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(dm.WRF50.dmu.state, 'lock', false)"
    },
    {
     "target": "alias(dm.WRF50.mode, 'mode', false)"
    },
    {
     "target": "alias(dm.WRF50.dmu.lrate,'lock rate 2min', false)"
    }
   ]
  },
  {
   "title": "50 Hz Info (synchronization period)",
   "type": "timeseries",
   "description": "mains vs. data master",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(dm.WRF50.mains.period, 'mains', false)"
    },
    {
     "target": "alias(dm.WRF50.dmu.period, '$dm', false)"
    }
   ]
  },
  {
   "title": "Cycles (2us diff in cycle length = 5mHz diff in cycle rate)",
   "type": "timeseries",
   "description": "Cycle rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(dm.WRF50.dmu.rate, '$dm', false)"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  },
  {
   "title": "RX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "RX packet rate of the localmaster WRS:\nprimary DM @wri15, backup DM @wri16, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.2.value), 'wri2 (distr.)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.3.value), 'wri3 (distr.)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.14.value), 'wri14 (DM sync)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.15.value), 'wri15 (primary DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.16.value), 'wri16 (backup DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.rxf.17.value), 'wri17 (service)', false)"
    }
   ]
  },
  {
   "title": "TX packet rate @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "TX packet rate of the localmaster WRS:\nprimary DM @wri15, backup DM @wri16, distribution WRSs @wri2-10, service WRS @wri17",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.2.value), 'wri2 (distr)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.3.value), 'wri3 (distr)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.14.value), 'wri14 (DM sync)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.15.value), 'wri15 (primary DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.16.value), 'wri16 (backup DM)', false)"
    },
    {
     "target": "alias(perSecond(icinga.$lm.Interfaces.perfdata.txf.17.value), 'wri17 (service)', false)"
    }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minimum time budget (switch layers 1-3, value > 400us: ok; in case of  a late message, the value is re-initialized)",
   "type": "timeseries",
   "description": "Minimum difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtmin, 2, 3)"
    }
   ]
  },
  {
   "title": "Average time budget",
   "type": "timeseries",
   "description": "Average difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtave, 2, 3)"
    }
   ]
  },
  {
   "title": "Late messages (switch layers 2-3)",
   "type": "timeseries",
   "description": "Number of the late messages in the UNILAC network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nlate, 2, 3)"
    }
   ]
  },
  {
   "title": "Total messages @ localmaster WRS - $lm",
   "type": "timeseries",
   "description": "Total number of messages in the UNILAC network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nmess, 2, 3)"
    }
   ]
  }
 ]
}