{
 "title": "WRS Temperature",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "WRS FPGA Temperature [Thresholds >= 60° Red, >= 70° Purple]",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.fpga.value), 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA Temperature",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.fpga.value), 1)"
    }
   ]
  },
  {
   "title": "WRS PSR Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.psr.value), 1)"
    }
   ]
  },
  {
   "title": "WRS PSL Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.psl.value), 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA Derivative Temperature ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(icinga.*.Temperature.perfdata.sensor.fpga.value, 1))"
    }
   ]
  },
  {
   "title": "WRS PLL Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.pll.value), 1)"
    }
   ]
  }
 ]
}