{
 "title": "GMT Gateways (INT)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gw", "query": "scuxl0432, scuxl0232, fel0077" }
  ]
 },
 "panels": [
  {
   "title": "Gateway MIL message rates - $gw",
   "type": "timeseries",
   "description": "Operation rates for WR MIL Gateways",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.rate10s, 1)"
    },
    {
     "target": "aliasByNode(dm.WRF50INT.dmu.rate, 1)"
    }
   ]
  },
  {
   "title": "Gateway number of sent MIL messages - All",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(gw.*.$gw.milnum, 1, 2)"
    }
   ]
  },
  {
   "title": "Gateway WR sync",
   "type": "timeseries",
   "description": "WR sync status (100=Tracking, 20=No sync, 0=others)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.status, 1)"
    },
    { "target": "dm.WRF50INT.sync" }
   ]
  },
  {
   "title": "Gateway - lm32 number of bursts, lates and 'slow'",
   "type": "timeseries",
   "description": "burst: distance between subsequent evts < 30us;\nlate: message delivered late by the eca;\nslow : lm32 wait4eca started too late",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.millate, 1,3)"
    },
    {
     "target": "aliasByNode(gw.*.$gw.nburst, 1,3)"
    },
    {
     "target": "aliasByNode(gw.*.$gw.nslow, 1, 3)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.nlates, 1,3)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.nslow, 1, 3)"
    }
   ]
  },
  {
   "title": "Gateway - lm32 message delivery time from ECA (act)",
   "type": "timeseries",
   "description": "if 'slow: offset 'start wait4eca' to 'end wait4eca';\nelse: offset 'deadline' to 'end wait4eca'",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "target": "aliasByNode(gw.*.$gw.tcom, 1)" },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tcom,1)"
    }
   ]
  },
  {
   "title": "Gateway - lm 32 'too slow' time (act)",
   "type": "timeseries",
   "description": "- slow time: by how much wait4eca started too late; max value should be < 480.0 us",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tslow, 1,3)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tslow, 1,3)"
    }
   ]
  },
  {
   "title": "Gateway - lm32 message delivery time from ECA (max)",
   "type": "timeseries",
   "description": "if 'slow: offset 'start wait4eca' to 'end wait4eca';\nelse: offset 'deadline' to 'end wait4eca'",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tcommax, 1)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tcommax,1)"
    }
   ]
  },
  {
   "title": "Gateway - lm 32 'too slow' time (max)",
   "type": "timeseries",
   "description": "- slow time: by how much wait4eca started too late; max value should be < 480.0 us",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tslowmax, 1,3)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tslowmax, 1,3)"
    }
   ]
  },
  {
   "title": "Gateway - lm32 message delivery time from ECA (min)",
   "type": "timeseries",
   "description": "if 'slow: offset 'start wait4eca' to 'end wait4eca';\nelse: offset 'deadline' to 'end wait4eca'",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tcommin, 1)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tcommin,1)"
    }
   ]
  },
  {
   "title": "Gateway - lm 32 'too slow' time (min)",
   "type": "timeseries",
   "description": "- slow time: by how much wait4eca started too late; max value should be < 480.0 us",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tslowmin, 1,3)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tslowmin, 1,3)"
    }
   ]
  },
  {
   "title": "Gateway - lm32 message processing time (act)",
   "type": "timeseries",
   "description": "time spent when handling the timing message after reception",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "target": "aliasByNode(gw.*.$gw.tproc, 1)" },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tproc, 1)"
    }
   ]
  },
  {
   "title": "Gateway eCPU stalls  (act)- $gw",
   "type": "timeseries",
   "description": "Stall, observation interval = 50000",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/500", "type": "math" }
   ]
  },
  {
   "title": "Gateway - lm32 message processing time (max)",
   "type": "timeseries",
   "description": "time spent when handling the timing message after reception",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tprocmax, 1)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tprocmax, 1)"
    }
   ]
  },
  {
   "title": "Gateway eCPU stalls (max) - $gw",
   "type": "timeseries",
   "description": "Stall, observation interval = 50000",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/500", "type": "math" }
   ]
  },
  {
   "title": "Gateway - lm32 message processing time (min)",
   "type": "timeseries",
   "description": "time spent when handling the timing message after reception",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.tprocmin, 1)"
    },
    {
     "target": "aliasByNode(gw.WRF50INT.dmu.tprocmin, 1)"
    }
   ]
  },
  {
   "title": "Gateway WR offset (includes latency)",
   "type": "timeseries",
   "description": "Offset between TAI (WR) and UTC",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(gw.*.$gw.offset, 1)"
    }
   ]
  }
 ]
}