{
 "title": "GMT UNILAC",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cm", "query": "uni.nw.*" },
   { "name": "cm_dl", "query": "uni.nw.*.*" },
   { "name": "cm_dl_port", "query": "uni.nw.*.*.*" },
   { "name": "pz", "query": "uni.pz.*" }
  ]
 },
 "panels": [
  { "title": "Pulsezentrale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TX messages - $pz",
   "type": "graph",
   "description": "Message rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "hertz", "label": "message rate" }
   ],
   "targets": [
    { "target": "uni.pz.$pz.messrate" }
   ]
  },
  {
   "title": "WR sync status",
   "type": "graph",
   "description": "WR sync status\n(100=Tracking, 20=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "uni.pz.*.wrsync" }
   ]
  },
  {
   "title": "Cycles - $pz",
   "type": "graph",
   "description": "Cycle rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "hertz", "label": "cycle rate" }
   ],
   "targets": [
    { "target": "uni.pz.$pz.mainsf" }
   ]
  },
  {
   "title": "Warnings - $pz",
   "type": "graph",
   "description": "Warnings count of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    { "target": "uni.pz.$pz.warncnt" }
   ]
  },
  { "title": "Network Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TX packets @ layer 1 switch - $cm",
   "type": "graph",
   "description": "TX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.nw.$cm.$cm_dl.$cm_dl_port.tx.rate10s, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "RX packets @ layer 1 switch- $cm",
   "type": "graph",
   "description": "RX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.nw.$cm.$cm_dl.$cm_dl_port.rx.rate10s, 2, 3, 4)"
    }
   ]
  }
 ]
}