{
 "title": "GMT WRS Temp by Location",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "BG2A_5N",
    "query": "nwt0013m66, nwt0029m66, nwt0037m66, nwt0082m66, nwt0083m66, nwt0099m66, nwt0283m66, nwt0284m66, nwt0465m66, nwt0486m66, nwt0032m66, nwt0098m66, nwt0117m66, nwt0316m66, nwt0014m66, nwt0021m66, nwt0024m66, nwt0076m66, nwt0077m66, nwt0078m66, nwt0079m66, nwt0479m66"
   },
   {
    "name": "VR1D_01",
    "query": "nwt0045m66, nwt0100m66, nwt0285m66, nwt0467m66, nwt0474m66"
   },
   {
    "name": "VR1X_40",
    "query": "nwt0478m66, nwt0285m66, nwt0292m66, nwt0293m66, nwt0294m66, nwt0317m66"
   },
   {
    "name": "TH2_X",
    "query": "nwt0022m66, nwt0026m66, nwt0038m66, nwt0041m66, nwt0048m66, nwt0122m66, nwt0081m66, nwt0485m66"
   },
   {
    "name": "BG_EPS",
    "query": "nwt0088m66, nwt0113m66, nwt0097m66, nwt0275m66, nwt0277m66, nwt0287m66, nwt0226m66, nwt0273m66"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "WRS FPGA temperature (BG2A.54..56)",
   "type": "timeseries",
   "description": "WRS temperatures in racks with similar thermal environment, central TOS racks in BG.2.009",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icinga.$BG2A_5N.Temperature.perfdata.sensor.fpga.value, 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (BG2C, BG2B, BG1A)",
   "type": "timeseries",
   "description": "WRS temperatures in racks with similar thermal environment, central TOS racks in BG.2.002, BG.2.001, BG.1.010b",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icinga.$BG_EPS.Temperature.perfdata.sensor.fpga.value, 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (VR1D_01)",
   "type": "timeseries",
   "description": "WRS temperatures in racks with similar thermal environment; central TOS at LSB6",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icinga.$VR1D_01.Temperature.perfdata.sensor.fpga.value, 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (VR1X_40)",
   "type": "timeseries",
   "description": "WRS temperatures in racks with similar thermal environment; TOS racks at LSB4",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icinga.$VR1X_40.Temperature.perfdata.sensor.fpga.value, 1)"
    }
   ]
  },
  {
   "title": "WRS FPGA temperature (TH2_X)",
   "type": "timeseries",
   "description": "WRS temperatures in racks with similar thermal environment; racks in CRYRING containers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icinga.$TH2_X.Temperature.perfdata.sensor.fpga.value, 1)"
    }
   ]
  }
 ]
}