{
 "title": "GMT UNILAC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cm", "query": "uni.nw.*" },
   { "name": "cm_dl", "query": "uni.nw.*.*" },
   { "name": "cm_dl_port", "query": "uni.nw.*.*.*" },
   { "name": "pz", "query": "uni.pz.*" }
  ]
 },
 "panels": [
  { "title": "Pulsezentrale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TX messages - $pz",
   "type": "graph",
   "description": "Message rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "hertz", "label": "message rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.messrate, 2)"
    }
   ]
  },
  {
   "title": "WR sync status",
   "type": "graph",
   "description": "WR sync status\n(100=Tracking, 20=No sync, 0=other)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.pz.*.wrsync, 2)"
    }
   ]
  },
  {
   "title": "cycles (2us diff in cycle length = 5mHz diff in cycle rate)- $pz",
   "type": "graph",
   "description": "Cycle rate of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "hertz", "label": "cycle rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.mainsf, 2)"
    }
   ]
  },
  {
   "title": "Warnings - $pz",
   "type": "graph",
   "description": "Warnings count of Pulsezentrale\n(cpu0=QR QL QN HLI HSI AT TK)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.pz.$pz.warncnt, 2)"
    }
   ]
  },
  { "title": "Network Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TX packets @ layer 1 switch - $cm",
   "type": "graph",
   "description": "TX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.nw.$cm.$cm_dl.$cm_dl_port.tx.rate10s, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "RX packets @ layer 1 switch- $cm",
   "type": "graph",
   "description": "RX packet rate of clock master (WR switch)",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "hertz", "label": "packet rate" }
   ],
   "targets": [
    {
     "target": "aliasByNode(uni.nw.$cm.$cm_dl.$cm_dl_port.rx.rate10s, 2, 3, 4)"
    }
   ]
  },
  { "title": "Network Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "late messages at layer 1 switch",
   "type": "graph",
   "description": "Number of the late actions in the UNI timing network",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nlate, 2, 3)"
    }
   ]
  },
  {
   "title": "total messages at layer 1",
   "type": "graph",
   "description": "Number of messages in the UNI timing network",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "# of messages @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.nmess, 2, 3)"
    }
   ]
  },
  {
   "title": "minimum time budget at layer 1 switch (value > 600us: ok; in case of  a late message, the value is re-initialized)",
   "type": "graph",
   "description": "Maximum difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "µs", "label": "time til deadline @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtmin, 2, 3)"
    }
   ]
  },
  {
   "title": "average time budget at layer 1 switch",
   "type": "graph",
   "description": "Average difference between deadline and actual time",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "µs", "label": "time til deadline @ ECA input" }
   ],
   "targets": [
    {
     "target": "aliasByNode(diag.UNI.*.*.dtave, 2, 3)"
    }
   ]
  }
 ]
}