{
 "title": "Icinga2 with Graphite",
 "description": "Icinga2 & Graphite Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname", "query": "icinga.*" },
   {
    "name": "pl",
    "label": "Packet loss",
    "query": "icinga.$hostname.host.perfdata.pl.*"
   },
   {
    "name": "rta",
    "label": "RTA",
    "query": "icinga.$hostname.host.perfdata.rta.*"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "icinga2.$hostname.services.disk.disk.perfdata.*"
   }
  ]
 },
 "panels": [
  { "title": "Performance data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packet loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$hostname.host.perfdata.pl.$pl, 1), 1)"
    }
   ]
  },
  {
   "title": "RTA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$hostname.host.perfdata.rta.$rta, 1), 1)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "content": "![alt text](https://www.icinga.org/wp-content/uploads/2014/06/logo_icinga_white-300x1161.png \"Icinga2\")\nExtend this dashboard by adding more services to your Icinga configuration. Correlate thresholds with performance data and maintenance works."
  },
  {
   "title": "Other metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Alive",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "target": "icinga2.$hostname.host.hostalive.metadata.state"
      }
     ]
    },
    {
     "title": "Ping4",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(icinga2.$hostname.services.ping4.ping4.perfdata.pl.value, 'packetloss')"
      },
      {
       "target": "alias(icinga2.$hostname.services.ping4.ping4.perfdata.rta.value, 'rta')"
      },
      {
       "target": "alias(icinga2.$hostname.services.ping4.ping4.perfdata.rta.warn, 'WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.ping4.ping4.perfdata.rta.crit, 'CRITICAL')"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.ping4.ping4.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(icinga2.$hostname.services.load.load.perfdata.load1.value, 6)"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load1.warn, 'load1-WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load1.crit, 'load1-CRITICAL')"
      },
      {
       "target": "aliasByNode(icinga2.$hostname.services.load.load.perfdata.load5.value, 6)"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load5.warn, 'load5-WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load5.crit, 'load5-CRITICAL')"
      },
      {
       "target": "aliasByNode(icinga2.$hostname.services.load.load.perfdata.load15.value, 6)"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load15.warn, 'load15-WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.load.load.perfdata.load15.crit, 'load15-CRITICAL')"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.load.load.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
     "content": "#### **Thresholds**\nThe thresholds shown here are the thresholds you configured in your Icinga2 configuration. Changing them will automatically also change them in this dashboard. When values exceed thresholds, it is an indicator that alerts have been sent from your Icinga2 monitoring system."
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(icinga2.$hostname.services.procs.procs.perfdata.procs.value, 'processes')"
      },
      {
       "target": "alias(icinga2.$hostname.services.procs.procs.perfdata.procs.warn, 'WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.procs.procs.perfdata.procs.crit, 'CRITICAL')"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.procs.procs.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    },
    {
     "title": "Free Swap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(icinga2.$hostname.services.swap.swap.perfdata.swap.value, 'swap')"
      },
      {
       "target": "alias(icinga2.$hostname.services.swap.swap.perfdata.swap.warn, 'WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.swap.swap.perfdata.swap.crit, 'CRITICAL')"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.procs.procs.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
     "content": "#### **Downtimes**\nWhen setting a downtime, for example in IcingaWeb or via API, it will be marked in the affected graph. To get a clean view, the graph legend will display downtimes only when they exist. Downtimes are usually set for maintenance work and are an indicator that graphed data is changing on purpose."
    },
    {
     "title": "Disk $disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(icinga2.$hostname.services.disk.disk.perfdata.$disk.max, 7)"
      },
      {
       "target": "alias(icinga2.$hostname.services.disk.disk.perfdata.$disk.value, 'free')"
      },
      {
       "target": "alias(icinga2.$hostname.services.disk.disk.perfdata.$disk.warn, 'WARNING')"
      },
      {
       "target": "alias(icinga2.$hostname.services.disk.disk.perfdata.$disk.crit, 'CRITICAL')"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.disk.disk.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    },
    {
     "title": "Users logged in",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(icinga2.$hostname.services.users.users.perfdata.users.value, 6)"
      },
      {
       "target": "alias(asPercent(removeBelowValue(icinga2.$hostname.services.procs.procs.metadata.downtime_depth, 1), 1), 'DOWNTIME')"
      }
     ]
    }
   ]
  }
 ]
}