{
 "title": "TTF - RTA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scu", "query": "icinga.wrn_scu*" },
   { "name": "pexaria", "query": "icinga.wrn_pexaria*" },
   { "name": "exploder", "query": "icinga.wrn_expl*" },
   { "name": "pmc", "query": "icinga.wrn_pmc*" },
   { "name": "amc", "query": "icinga.wrn_amc*" },
   { "name": "vme", "query": "icinga.wrn_vme*" }
  ]
 },
 "panels": [
  {
   "title": "TTF - RTA - SCU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$scu.host.perfdata.rta.value, 1000), 1)"
    }
   ]
  },
  {
   "title": "TTF - RTA - VME",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$vme.host.perfdata.rta.value, 1000), 1)"
    }
   ]
  },
  {
   "title": "TTF - RTA - Pexarria",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$pexaria.host.perfdata.rta.value, 1000), 1)"
    }
   ]
  },
  {
   "title": "TTF - RTA - Exploder",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$exploder.host.perfdata.rta.value, 1000), 1)"
    }
   ]
  },
  {
   "title": "TTF - RTA - AMC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.wrn_amc127797t_node.host.perfdata.rta.*, 1000), 1)"
    }
   ]
  },
  {
   "title": "TTF - RTA - PMC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(icinga.$pmc.host.perfdata.rta.value, 1000), 1)"
    }
   ]
  }
 ]
}