{
 "title": "TTF_metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "ttf.*" },
   { "name": "dev", "query": "ttf.*.*" },
   { "name": "type", "query": "ttf.*.*.*" },
   { "name": "scu", "query": "ttf.*.*.scu*" },
   { "name": "pexarria", "query": "ttf.*.*.pexarria*" },
   { "name": "exploder", "query": "ttf.*.*.exploder*" },
   { "name": "pmc", "query": "ttf.*.*.pmc*" },
   { "name": "vetar", "query": "ttf.*.*.vetar*" }
  ]
 },
 "panels": [
  { "title": "Offset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTF - Offset - SCU - $scu",
   "type": "graph",
   "description": "Offset between TAI and UTC time",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Offset, sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$scu.node.offset, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Offset - Pexarria - $pexarria",
   "type": "graph",
   "description": "Offset between TAI and UTC time",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Offset, sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$pexarria.node.offset, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Offset - PMC - $pmc",
   "type": "graph",
   "description": "Offset between TAI and UTC time",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Offset, sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$pmc.*.offset, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Offset - Vetar - $vetar",
   "type": "graph",
   "description": "Offset between TAI and UTC time",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Offset, sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$vetar.*.offset, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Offset - Exploder - $exploder",
   "type": "graph",
   "description": "Offset between TAI and UTC time",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Offset, sec" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$exploder.*.offset, 1), 2)"
    }
   ]
  },
  { "title": "Temperature (FPGA)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TTF - Temperature - Pexarria - $pexarria",
   "type": "graph",
   "description": "FPGA device temperature",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$pexarria.node.temp, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Temperature - Exploder - $exploder",
   "type": "graph",
   "description": "FPGA device temperature",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$exploder.*.temp, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Temperature - PMC - $pmc",
   "type": "graph",
   "description": "FPGA device temperature",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$pmc.*.temp, 1), 2)"
    }
   ]
  },
  { "title": "Temperature (board, 1-wire)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "TTF - Board temperature - Pexarria - $pexarria",
   "type": "graph",
   "description": "Board temperature from 1-wire sensor",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$pexarria.*.temp1w, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Board temperature - Exploder - $exploder",
   "type": "graph",
   "description": "Board temperature from 1-wire sensor",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$exploder.*.temp1w, 1), 2)"
    }
   ]
  },
  {
   "title": "TTF - Board temperature - SCU - $scu",
   "type": "graph",
   "description": "Board temperature from 1-wire sensor",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature, degree" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(ttf.$host.$dev.$scu.*.temp1w, 1), 2)"
    }
   ]
  }
 ]
}