{
 "title": "WRS Fan Diagnostic",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "WRS PLL Temperature [Thresholds >=55° Yellow,  >= 60° Red, >= 70° Purple]",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.sensor.pll.*), 1)"
    }
   ]
  },
  {
   "title": "WRS PWM Fans [Thresholds >= 60% Blue]",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(icinga.*.Temperature.perfdata.fan.pwm_val.value), 1)"
    }
   ]
  },
  {
   "title": "WRS PWM Fans (all)",
   "type": "timeseries",
   "description": "shown are WRSs with PWM value higher than 40%",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "averageAbove(aliasByNode(icinga.*.Temperature.perfdata.fan.pwm_val.value, 1), 40)"
    }
   ]
  },
  {
   "title": "WRS PLL Temperatur (all)",
   "type": "timeseries",
   "description": "WRSs with PLL temperature 55°C or above",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "averageAbove(aliasByNode(icinga.*.Temperature.perfdata.sensor.pll.value, 1), 54)"
    }
   ]
  },
  {
   "title": "WRS FPGA Temperature (all)",
   "type": "timeseries",
   "description": "WRSs with FPGA temperature 55°C or above.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "averageAbove(aliasByNode(icinga.*.Temperature.perfdata.sensor.fpga.value, 1), 54)"
    }
   ]
  }
 ]
}